project_id = "aavlayzfaafuwquhhbcx"

[functions.verify-role]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.notify-proposal-submitted]
verify_jwt = false

[functions.notify-submission-response]
verify_jwt = false
